name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1
    - uses: actions/checkout@v2
    # Needed because this project has references to iOS-specific frameworks
    # such as UIKit, AVFoundation and CoreMotion.
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12 Pro' -scheme 'SwiftttCamera-Package'
